# This notebook can be used to interact a bit with the functions

In [1]:
from src.generate_random_crystals import generate_random_crystal_structure_from_composition
from pyxtal import pyxtal

# very annoying, but it seems this is the best way to visualize a pymatgen structure
def pymatgen_to_pyxtal(crystal):
    crystal.to(filename="structure.cif")
    pyxtal_crystal = pyxtal()
    pyxtal_crystal.from_seed("structure.cif")
    return pyxtal_crystal

### 1. Test randomly generating crystal structures

In [12]:
my_crystal = generate_random_crystal_structure_from_composition(['Li', 'O', 'Cu'], [0.8, 0.1, 0.1])
pyxtal_crystal = pymatgen_to_pyxtal(my_crystal)
pyxtal_crystal.show()

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

### 2. Test crossover of two crystal

In [14]:
species, num_species = ['Li', 'O'], [0.8, 0.2]
crystal1, crystal2 = generate_random_crystal_structure_from_composition(species, num_species), generate_random_crystal_structure_from_composition(species, num_species)
pymatgen_to_pyxtal(crystal1).show()

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [15]:
pymatgen_to_pyxtal(crystal2).show()

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [17]:
from src.evolutionary_algorithm.crossover_operator import crossover_operator

child_crystal = crossover_operator(crystal1, crystal2)
pymatgen_to_pyxtal(child_crystal).show()

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

### 3. Test mutation of crystal structure

In [4]:
from src.evolutionary_algorithm.mutate_operator import mutate_operator
my_crystal = generate_random_crystal_structure_from_composition(['Li', 'O', 'Cu'], [0.8, 0.1, 0.1])
pymatgen_to_pyxtal(my_crystal).show()

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [6]:
my_crystal = mutate_operator(my_crystal, rescaling_volume=my_crystal.volume)
pymatgen_to_pyxtal(my_crystal).show()

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [6]:
pyxtal_crystal = pyxtal()
pyxtal_crystal.from_seed("outputs/best_structure_9.cif")
pyxtal_crystal.show(super_cell=(2,2,2))

TypeError: display_atomic() got an unexpected keyword argument 'super_cell'

In [9]:
my_crystal = generate_random_crystal_structure_from_composition(['Li', 'O', 'Cu'], [0.8, 0.1, 0.1])
pymatgen_to_pyxtal(my_crystal).show()

/home/rhjvanworkum/miniconda3/envs/mat/lib/python3.11/site-packages/pymatgen/io/cif.py:1290: UserWarning: Issues encountered while parsing CIF: 4 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: " + "\n".join(self.warnings))


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [18]:
import numpy as np
import random
from scipy.spatial.transform import Rotation as R
from pymatgen.core import Structure

slicing_dim = random.randint(0,2)
slicing_threshold = random.uniform(0, 1) * my_crystal.frac_coords[:, slicing_dim].max()

print(my_crystal.frac_coords)

slicing_direction = np.zeros(3)
slicing_direction[slicing_dim] = 1


# # Generate a random 3D vector (the slicing plane normal)
# random_direction = np.array([1.0, 0.0, 0.0])
# # random_direction /= np.linalg.norm(random_direction)  # Normalize to get a unit vector

# # Step 1: Find the rotation matrix that aligns the random direction to the z-axis
# z_axis = np.array([0, 0, 1])
# rotation, _ = R.align_vectors([random_direction], [z_axis])

# # Step 2: Rotate the atomic positions of the structure
# coords = np.array([site.frac_coords for site in my_crystal.sites])
# rotated_coords = rotation.apply(coords)

# # Step 3: Select a slice by cutting along the new z-axis (which was aligned with the random direction)
# # Here, we slice by keeping atoms with z-coordinates between 0 and 0.5
# slice_indices = np.where((rotated_coords[:, 2] >= 0) & (rotated_coords[:, 2] <= 1.0))[0]

# # Create the sliced structure by keeping only the selected atoms
# sliced_structure = Structure(lattice=my_crystal.lattice, species=[my_crystal[i].specie for i in slice_indices],
#                              coords=[my_crystal[i].frac_coords for i in slice_indices])

# pymatgen_to_pyxtal(sliced_structure).show()

[[ 0.00000000e+00  0.00000000e+00  1.84468194e-01]
 [ 3.33333333e-01  6.66666667e-01  4.85708490e-01]
 [ 6.66666667e-01  3.33333333e-01  4.85708490e-01]
 [ 8.56273359e-01  1.89868711e-17  9.15409544e-01]
 [ 0.00000000e+00  8.56273359e-01  9.15409544e-01]
 [-8.56273359e-01 -8.56273359e-01  9.15409544e-01]
 [ 5.43159474e-01 -2.72659432e-17  5.51194591e-02]
 [ 0.00000000e+00  5.43159474e-01  5.51194591e-02]
 [ 4.56840526e-01  4.56840526e-01  5.51194591e-02]
 [ 0.00000000e+00  0.00000000e+00  7.02303610e-01]]


Structure Summary
Lattice
    abc : 7.117761492443814 8.04896749327052 7.117992057578358
 angles : 90.0 90.0 90.0
 volume : 407.7942555599328
      A : 7.117761492443814 4.3583719144078025e-16 4.3583719144078025e-16
      B : 0.0 8.04896749327052 4.928571138537419e-16
      C : 0.0 0.0 7.117992057578358
    pbc : True True True
PeriodicSite: Cu (0.0, 0.0, 0.7419) [0.0, 0.0, 0.1042]
PeriodicSite: Li (1.464, -3.321, 6.153) [0.2057, -0.4126, 0.8644]
PeriodicSite: Li (5.653, -3.321, 6.153) [0.7943, -0.4126, 0.8644]